---
- name: "Add Node.js from source"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
- name: "Install Node.js 14"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "Install forever Globally to run node app"
  npm:
    name: forever
    global: yes
    state: present

- name: "Install ts-node Globally"
  npm:
    name: ts-node
    global: yes